version: '3'
services:
  database:
    image: mysql:8.0.27
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: secret

    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
